version: "3.8"
services:
  postgres-shorten-url-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shorten_url_db
    ports:
      - "5500:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - shorten-url-shared

volumes:
  db_data:

networks:
  shorten-url-shared:
    name: shorten-url-shared
    driver: bridge
