name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker With buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shorten-url:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy compose file to server
        run: |
          ssh root@${{ secrets.SERVER_HOST }} "mkdir -p /root/shorten-url"
          scp docker-compose.yaml root@${{ secrets.SERVER_HOST }}:/root/shorten-url/
          scp docker-compose-db.yaml root@${{ secrets.SERVER_HOST }}:/root/shorten-url/

      - name: Create env file on server
        run: |
          ssh root@${{ secrets.SERVER_HOST }} "
            cat > /root/shorten-url/.env << EOF
            PORT=8085
            GIN_MODE=release
            APP_ENV=production
            APP_NAME=shorten-url

            SERVER_HOST=localhost
            SERVER_PORT=8085

            DB_DRIVER=postgres
            DB_HOST=postgres-shorten-url-db
            DB_PORT=5432
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD}}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_SSL_MODE=disable

            REDIS_HOST=localhost
            REDIS_PORT=6379
            REDIS_PASSWORD=
            REDIS_DB=0

            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=24h

            API_BASE_URL=${{ secrets.API_BASE_URL }}
          "

      - name: Deploy to server with Docker Compose
        run: |
          ssh root@${{ secrets.SERVER_HOST }} "
            cd /shorten-url
            docker-compose -f docker-compose-db.yaml up -d
            docker-compose -f docker-compose.yaml pull
            docker-compose -f docker-compose.yaml up -d --remove-orphans
            echo 'âœ… Deployment successfully'
          "

      - name: Health Check
        run: |
          sleep 10
          curl -f http://${{ secrets.SERVER_HOST }}:8085/health || exit 1

      # - name: Discord notification
      #   if: always()
      #   run: |
      #     STATUS="${{ job.status }}"
      #     curl -H "Content-Type: application/json" \
      #          -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
      #          -d "{\"content\": \"ðŸš€ Deploy completed! Status: $STATUS\"}" \
